apiVersion: v1
entries:
  apisecurity:
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-18T16:41:55.509913-03:00"
    description: Chart de Helm para la aplicación apisecurity
    digest: b6bf9568b6ac3d4e10465c4fcb6bd77c3633c95da323f5d114bf211cee305ce1
    name: apisecurity
    type: application
    urls:
    - apisecurity-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-18T16:41:55.5096758-03:00"
    description: Chart de Helm para la aplicación apisecurity
    digest: 898b8f1be07b7166ab00d021109ec7fc941e94313e7363c6aa1cd8464b5f145b
    name: apisecurity
    type: application
    urls:
    - apisecurity-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-18T16:41:55.5093721-03:00"
    description: Chart de Helm para la aplicación apisecurity
    digest: 69607d22444ce6019bcc521e705065a0e46086c21da1560d41a5038efec40a42
    name: apisecurity
    type: application
    urls:
    - apisecurity-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-18T16:41:55.5091462-03:00"
    description: Chart de Helm para la aplicación apisecurity
    digest: 5d2afaa21b2e70725e6ac105264b571d4f226f15b1f9fc1f2c5173ec9c40bbf6
    name: apisecurity
    type: application
    urls:
    - apisecurity-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-18T16:41:55.5089034-03:00"
    description: Chart de Helm para la aplicación apisecurity
    digest: 494578c3646ab780d81ac9eeda3383945d2a175bb0c280348cf4f036e619e88c
    name: apisecurity
    type: application
    urls:
    - apisecurity-0.1.0.tgz
    version: 0.1.0
  example-app:
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-18T16:41:55.5101154-03:00"
    description: Chart de Helm para la app example-app
    digest: 81a0f3a1886480fb4fdec60834c6000beee382d12243d779be32a6358a7e7002
    name: example-app
    type: application
    urls:
    - example-app-0.1.0.tgz
    version: 0.1.0
  loginapp:
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-18T16:41:55.5105271-03:00"
    description: Chart de Helm para la app loginapp
    digest: d39eae08ebc24947e68e3f196d292c37c382c7d25de389abcf3fb449d1c51198
    name: loginapp
    type: application
    urls:
    - loginapp-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-18T16:41:55.5103001-03:00"
    description: A Helm chart for Kubernetes
    digest: dbd9d5ec8d119952d3eb29fb93a771719d62c02fc9b70d6fef439f46c270bbf8
    name: loginapp
    type: application
    urls:
    - loginapp-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-18T16:41:55.5085259-03:00"
