apiVersion: v1
entries:
  apisecurity:
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-05T13:06:22.5584129-03:00"
    description: Chart de Helm para la aplicación apisecurity
    digest: 5d2afaa21b2e70725e6ac105264b571d4f226f15b1f9fc1f2c5173ec9c40bbf6
    name: apisecurity
    type: application
    urls:
    - apisecurity-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-05T13:06:22.5579366-03:00"
    description: Chart de Helm para la aplicación apisecurity
    digest: 494578c3646ab780d81ac9eeda3383945d2a175bb0c280348cf4f036e619e88c
    name: apisecurity
    type: application
    urls:
    - apisecurity-0.1.0.tgz
    version: 0.1.0
  example-app:
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-05T13:06:22.5586299-03:00"
    description: Chart de Helm para la app example-app
    digest: c83876f7c85f49f459fb9753d09bce1796e52f64cadffd5c9164ca85b79ea6d6
    name: example-app
    type: application
    urls:
    - example-app-0.1.0.tgz
    version: 0.1.0
  loginapp:
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-05T13:06:22.5597049-03:00"
    description: Chart de Helm para la app loginapp
    digest: a43ed536cb76ff34b72e4b9abcc47ee9930c9a829abc5268efa3cee7d1a4cb77
    name: loginapp
    type: application
    urls:
    - loginapp-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: latest
    created: "2021-10-05T13:06:22.5591553-03:00"
    description: A Helm chart for Kubernetes
    digest: dbd9d5ec8d119952d3eb29fb93a771719d62c02fc9b70d6fef439f46c270bbf8
    name: loginapp
    type: application
    urls:
    - loginapp-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-05T13:06:22.5572586-03:00"
